# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoBackendColumnToggle\:
        resource: ../src/
        exclude:
            - ../src/ContaoManager/
            - ../src/DependencyInjection/
            - ../src/MarkocupicContaoBackendColumnToggle.php

    Markocupic\ContaoBackendColumnToggle\Controller\BackendController\ColumnToggleController:
        public: true
        tags: ['controller.service_arguments']
