services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoBackendColumnToggle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Model}'

    Markocupic\ContaoBackendColumnToggle\Controller\ColumnToggleController:
        public: true
        tags: [ 'controller.service_arguments' ]
